USE_LR_PARSER

prog

(* ====================================== Statements ========= *)
<prog>               ::= <stmtList>                          .

<stmtList> ::= <epsilon>
| <stmt> ";"  <stmtList>                            .

<epsilon>  ::= .

<stmt> ::= <dec>                                           .

<dec> ::= "int" id                                              .