USE_LR_PARSER

prog

(* ====================================== Statements ========= *)
<prog>               ::= <stmtList>                          .

<stmtList> ::= <epsilon>
| <stmt> ";"  <stmtList>                            .

<epsilon>  ::= .

<stmt> ::= <dec>  
         | <assign>  
         | <block>  .

<dec> ::= "int" id   
         | "bool" id                                           .

<assign> ::= id "=" integer .

<block> ::= "{" <stmtList> "}" .
